#pragma once

/*DONT EDIT THIS FILE! autogenerated code by XlibFactoryBuilder 1.0.2.3*/

#include <list>
#include <StdString.h>

#include "Classes/Interfaces/Interface_RS232.h"
#include "Classes/Interfaces/Interface_USB.h"

class CInterfaceFactory
{
public:
	static BOOL GetAllIdentifiers(std::list<CStdString>& p_rTargets);
	static BOOL CreateInstance(CStdString p_Name, CInterfaceBase*& p_rpInstance);
};
