#pragma once

/*DONT EDIT THIS FILE! autogenerated code by XlibFactoryBuilder 1.0.2.3*/

#include <list>
#include <StdString.h>

#include "../GatewayToDevice/CANopen/GatewayCANopenToEpos.h"
#include "../GatewayToDevice/CANopen/GatewayCANopenToEsam.h"
#include "../GatewayToDevice/CANopen/GatewayCANopenToEpos2.h"
#include "../GatewayToDevice/CANopen/GatewayCANopenToEsam2.h"

class CProtocolStackCANopenToDFactory
{
public:
	static BOOL GetAllIdentifiers(std::list<CStdString>& p_rTargets);
	static BOOL CreateInstance(CStdString p_Name, CGatewayPStoDCS*& p_rpInstance);
};
