#pragma once

/*DONT EDIT THIS FILE! autogenerated code by XlibFactoryBuilder 1.0.2.3*/

#include <list>
#include <StdString.h>

#include "../Gateway/Epos2/GatewayEpos2ToMaxonSerialV1.h"
#include "../Gateway/Epos2/GatewayEpos2ToMaxonSerialV2.h"
#include "../Gateway/Epos2/GatewayEpos2ToCANopen.h"

class CDeviceEpos2Factory
{
public:
	static BOOL GetAllIdentifiers(std::list<CStdString>& p_rTargets);
	static BOOL CreateInstance(CStdString p_Name, CGatewayDCStoPS*& p_rpInstance);
};
