#pragma once

/*DONT EDIT THIS FILE! autogenerated code by XlibFactoryBuilder 1.0.2.3*/

#include <list>
#include <StdString.h>

#include "Classes/ProtocolStacks/ProtocolStack_MaxonSerialV1.h"
#include "Classes/ProtocolStacks/ProtocolStack_MaxonSerialV2.h"
#include "Classes/ProtocolStacks/ProtocolStack_CANopen.h"
#include "Classes/ProtocolStacks/ProtocolStack_InfoteamSerial.h"

class CProtocolStackFactory
{
public:
	static BOOL GetAllIdentifiers(std::list<CStdString>& p_rTargets);
	static BOOL CreateInstance(CStdString p_Name, CProtocolStackBase*& p_rpInstance);
};
